### ISSUE TITLE
Append does not load existing goldenrun_data

### ISSUE THREAD

**Issue by aewag** [Fraunhofer-AISEC/archie#10]
If the append flag is set, the goldenrun is not executed [1]. Thus, the goldenrun_data is not created. Any existing data in the output.hdf5 or from somewhere else is as well not loaded. This leads to huge output.hdf5 files in the output mode as the results cannot be filtered. I would suggest to store the goldenrun results into a file and load if the append flag is set.

[1] https://github.com/Fraunhofer-AISEC/archie/blob/master/controller.py#L208

**Comment by tibersam** [comment]
In the development the append flag was proposed and at first implemented, but then ignored in reworkings and extensions of the tool. This is a bug that is not intended.
I have seen your proposed fix, but i am not sure if this is the way to go. The Goldenrun is already stored inside of the hdf5 file. But i want the tool to be flexible, meaning if another storing method is used that the user can chose to do so. Instead of storing goldenrun data inside a seperate file, maybe to extend the hdf5logger to have a function to retrieve the goldenrun data. If another storing method is used, this function can be replaced by the user.

**Comment by aewag** [comment]
> In the development the append flag was proposed and at first implemented, but then ignored in reworkings and extensions of the tool. This is a bug that is not intended.

The append feature is actually quite a nice feature. Especially with big experiments as the time consuming pre- & godenrun phase can be skipped.

> I have seen your proposed fix, but i am not sure if this is the way to go. The Goldenrun is already stored inside of the hdf5 file. But i want the tool to be flexible, meaning if another storing method is used that the user can chose to do so. Instead of storing goldenrun data inside a seperate file, maybe to extend the hdf5logger to have a function to retrieve the goldenrun data. If another storing method is used, this function can be replaced by the user.

Restoring the goldenrun_data from the hdf5 file was my first approach. But writing a parser for the hdf5 file took too much time. I agree that the doubled data is not the nicest approach, but it is straightforward and simple.

In the current case with big experiments it creates an additional file with 500 KB, which is quite acceptable in terms of size.

What do you think about having this in as a temporary solution to allow the append mode to be functional?

**Comment by tibersam** [comment]
As a temporary solution yes, but please add a comment to state this. Somthing like XXX to be removed by better solution or something along the way.

**Comment by aewag** [comment]
Updated:
https://github.com/aewag/archie/commit/dfd3d2d1c355f48ed33bd9e63692ea01f129bc95#diff-00066c2c6a38edb38037523eac2c0f6f4e2c7801786b691402bb684046b81956R210
