### ISSUE TITLE
Use of instruction overwrite to replace instruction before it is executed, with trigger address set to -1.

### ISSUE THREAD

**Issue by e-shreve-ti** [Fraunhofer-AISEC/archie#18]
I've been unable to create a fault matching the description above. It seems that the combination of setting trigger_address to [-1] and trigger_counter to [0] is not a supported combination? Is there a way to do this? Here is an example fault description:

				{
					"fault_address"		: [134217962, 134217972, 1],
					"fault_type"		: "instruction",
					"fault_model"		: "overwrite",
					"fault_livespan"	        : [3],
					"fault_mask"		: [191], 
					"trigger_address"	: [-1],
					"trigger_counter"	: [0],
					"num_bytes"		: [2]
				}

**Comment by tibersam** [comment]
Hi e-shrevi-ti,

This case should be possible. The qemu plugin can handle this. I am looking into the issue and will come back to you shortly.

**Comment by tibersam** [comment]
Fixed the special case of instruction fault and trigger hitcounter == 0.

**Comment by e-shreve-ti** [comment]
PR 19 doesn't seem to have fully addressed this yet, but perhaps PR 23 will? I'll try to get some more time to test further later this week. However, what I see after PR 19 was merged is that the console output indicates the experiments are running as I would expect. But, the results in the memory dumps are not what I expect (they indicate that instructions were not replaced by NOPs.)

**Comment by tibersam** [comment]
Are you looking into a memory dump defined with the fault.json? They are dumped at the defined end point. If you have lifetime set to nonzero, it will revert the changes made after the specified instructions. In the example above it is set to 3, therefore after 3 instructions the fault is reverted and you can not observe it in this memorydump. 

However during the injection, ARCHIE adds a new memorydump containing only the changed bytes before the injection, after the injection and after the reversion. Can you look into your data if those memorydumps where created?

Also a new table is added for each instruction fault called tbfaulted. It will collect the faulted assembly after the first execution, can you look into this data if the NOP instruction can be found there?

Also maybe you are not observing any changes in the execution of target because lifetime is set/to short?

**Comment by e-shreve-ti** [comment]
I am looking at a memory dump but not of memory that archie would be directly changing. Instead it is of memory that the code would change _if_ a NOP was inserted and executed instead of a branch instruction.

Looking at the logs, I'm seeing "[Info]: fault trigger address: 0xffffffffffffffff" is that to be expected or should an actual address be listed there?

**Comment by tibersam** [comment]
In your case (instruction fault, trigger hitcounter zero) the value of the fault trigger address is not used. It is 0xFFFFFFFFFFFFFFFF as the plugin recieves -1 as value.

I think the problem you are having is a misunderstanding/misconfiguration:
If you want to insert the fault directly at start set trigger hitcounter to zero, but make sure that the lifetime is either zero (permanent) or long enough that the faulted instruction is executed before it is reversed. If for example the faulted instruction is 100 instruction cycles after injection of the fault but your lifetime is < 100 archie reverts the fault before the instruction is executed => not fault can be observed.
If the faulted instruction is later in the section you are looking at and the fault should be injected at the first execution, you can set the trigger hitcounter to 1. Archie then will trigger on the instruction before the first execution of the target instruction you want to NOP. It then replaces the instruction with NOP. QEMU then reads the instruction as a NOP. Two instructions after the NOP instruction archie will then replace the NOP with the original instruction (lifetime 3). 

Looking on your example configuration you probably want to set trigger hitcounter to 1 instead of 0. This is just a guess as i lack the context your fault is injected into.

Near the beginning of the logoutput you should see some messages like these below. This shows a successful triggering for a fault injection. Can you find them in the logs?
[SINGLESTEP]: increase request
[SINGLESTEP]: requests 1  
[Fault] Inject instruction fault

**Comment by e-shreve-ti** [comment]
@tibersam, thank you for the help.

Setting trigger_counter to 1 has allowed me to move forward with my experiments.

**Comment by tibersam** [comment]
Glad i could help.

**Comment by aewag** [comment]
@tibersam thanks for the support! :+1: 

@e-shreve-ti as the issue seems to be resolved, I would close this issue for now, please re-open (or create a new one, if not related to this).
